
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.007365
     time (cpu & wall) for ordering          =        0.187500        0.417300
     time (cpu & wall) for other matrix prep =        0.046875        0.039003
     time (cpu & wall) for value input       =        0.015625        0.011128
     time (cpu & wall) for matrix distrib.   =        0.046875        0.056680
     time (cpu & wall) for numeric factor    =        0.046875        0.098619
     computational rate (gflops) for factor  =       27.874211       13.249005
     time (cpu & wall) for numeric solve     =        0.015625        0.010326
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =      2

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.008065
     time (cpu & wall) for matrix distrib.   =        0.062500        0.048627
     time (cpu & wall) for numeric factor    =        0.046875        0.084663
     computational rate (gflops) for factor  =       27.874211       15.433031
     time (cpu & wall) for numeric solve     =        0.015625        0.008605
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =      3

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.007961
     time (cpu & wall) for matrix distrib.   =        0.031250        0.047966
     time (cpu & wall) for numeric factor    =        0.093750        0.093497
     computational rate (gflops) for factor  =       13.937105       13.974774

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =      4

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.010946
     time (cpu & wall) for matrix distrib.   =        0.015625        0.050136
     time (cpu & wall) for numeric factor    =        0.078125        0.093629
     computational rate (gflops) for factor  =       16.724526       13.955072
     time (cpu & wall) for numeric solve     =        0.015625        0.010586
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =      5

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.010977
     time (cpu & wall) for matrix distrib.   =        0.031250        0.051192
     time (cpu & wall) for numeric factor    =        0.062500        0.092948
     computational rate (gflops) for factor  =       20.905658       14.057361

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =      6

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.009385
     time (cpu & wall) for matrix distrib.   =        0.046875        0.048003
     time (cpu & wall) for numeric factor    =        0.125000        0.102732
     computational rate (gflops) for factor  =       10.452829       12.718602
     time (cpu & wall) for numeric solve     =        0.031250        0.010017
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =      7

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.007076
     time (cpu & wall) for matrix distrib.   =        0.046875        0.048858
     time (cpu & wall) for numeric factor    =        0.062500        0.091339
     computational rate (gflops) for factor  =       20.905658       14.304960

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =      8

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.011003
     time (cpu & wall) for matrix distrib.   =        0.031250        0.048621
     time (cpu & wall) for numeric factor    =        0.078125        0.119180
     computational rate (gflops) for factor  =       16.724526       10.963325

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =      9

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.005727
     time (cpu & wall) for matrix distrib.   =        0.046875        0.046530
     time (cpu & wall) for numeric factor    =        0.078125        0.091428
     computational rate (gflops) for factor  =       16.724526       14.291098

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =     10

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.011779
     time (cpu & wall) for matrix distrib.   =        0.031250        0.047348
     time (cpu & wall) for numeric factor    =        0.062500        0.096386
     computational rate (gflops) for factor  =       20.905658       13.555976

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =     11

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.005862
     time (cpu & wall) for matrix distrib.   =        0.015625        0.042504
     time (cpu & wall) for numeric factor    =        0.062500        0.079474
     computational rate (gflops) for factor  =       20.905658       16.440663

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =     12

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.010871
     time (cpu & wall) for matrix distrib.   =        0.031250        0.052026
     time (cpu & wall) for numeric factor    =        0.078125        0.094947
     computational rate (gflops) for factor  =       16.724526       13.761400

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =     13

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.005700
     time (cpu & wall) for matrix distrib.   =        0.031250        0.046829
     time (cpu & wall) for numeric factor    =        0.078125        0.096738
     computational rate (gflops) for factor  =       16.724526       13.506678

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =     14

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.007103
     time (cpu & wall) for matrix distrib.   =        0.046875        0.045252
     time (cpu & wall) for numeric factor    =        0.031250        0.100653
     computational rate (gflops) for factor  =       41.811316       12.981217

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =     15

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.010885
     time (cpu & wall) for matrix distrib.   =        0.015625        0.042188
     time (cpu & wall) for numeric factor    =        0.078125        0.091564
     computational rate (gflops) for factor  =       16.724526       14.269809

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =     16

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.011704
     time (cpu & wall) for matrix distrib.   =        0.031250        0.048529
     time (cpu & wall) for numeric factor    =        0.062500        0.078040
     computational rate (gflops) for factor  =       20.905658       16.742764

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =     17

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.011387
     time (cpu & wall) for matrix distrib.   =        0.015625        0.046416
     time (cpu & wall) for numeric factor    =        0.062500        0.093992
     computational rate (gflops) for factor  =       20.905658       13.901266

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =     18

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.010412
     time (cpu & wall) for matrix distrib.   =        0.031250        0.049016
     time (cpu & wall) for numeric factor    =        0.078125        0.080510
     computational rate (gflops) for factor  =       16.724526       16.229166
     time (cpu & wall) for numeric solve     =        0.031250        0.009370
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =     19

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.010939
     time (cpu & wall) for matrix distrib.   =        0.062500        0.051749
     time (cpu & wall) for numeric factor    =        0.031250        0.092896
     computational rate (gflops) for factor  =       41.811316       14.065230

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =     20

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.007528
     time (cpu & wall) for matrix distrib.   =        0.046875        0.048106
     time (cpu & wall) for numeric factor    =        0.031250        0.091636
     computational rate (gflops) for factor  =       41.811316       14.258581

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =     21

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.011017
     time (cpu & wall) for matrix distrib.   =        0.031250        0.047114
     time (cpu & wall) for numeric factor    =        0.078125        0.088452
     computational rate (gflops) for factor  =       16.724526       14.771845
     time (cpu & wall) for numeric solve     =        0.015625        0.008988
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =     22

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.012215
     time (cpu & wall) for matrix distrib.   =        0.000000        0.047205
     time (cpu & wall) for numeric factor    =        0.015625        0.093692
     computational rate (gflops) for factor  =       83.622632       13.945748

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =     23

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.007621
     time (cpu & wall) for matrix distrib.   =        0.000000        0.049130
     time (cpu & wall) for numeric factor    =        0.078125        0.090440
     computational rate (gflops) for factor  =       16.724526       14.447187
     time (cpu & wall) for numeric solve     =        0.015625        0.009792
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =     24

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.007347
     time (cpu & wall) for matrix distrib.   =        0.046875        0.049717

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =     25

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.005704
     time (cpu & wall) for matrix distrib.   =        0.031250        0.045455
     time (cpu & wall) for numeric factor    =        0.046875        0.091898
     computational rate (gflops) for factor  =       27.874211       14.217946
     time (cpu & wall) for numeric solve     =        0.015625        0.008904
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =     26

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.008203
     time (cpu & wall) for matrix distrib.   =        0.031250        0.048888
     time (cpu & wall) for numeric factor    =        0.078125        0.089281
     computational rate (gflops) for factor  =       16.724526       14.634717
     time (cpu & wall) for numeric solve     =        0.031250        0.009704
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =     27

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.005705
     time (cpu & wall) for matrix distrib.   =        0.015625        0.048892
     time (cpu & wall) for numeric factor    =        0.093750        0.092433
     computational rate (gflops) for factor  =       13.937105       14.135699

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =     28

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.010958
     time (cpu & wall) for matrix distrib.   =        0.046875        0.046361
     time (cpu & wall) for numeric factor    =        0.046875        0.086491
     computational rate (gflops) for factor  =       27.874211       15.106869

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =     29

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.010914
     time (cpu & wall) for matrix distrib.   =        0.015625        0.048510
     time (cpu & wall) for numeric factor    =        0.015625        0.076030
     computational rate (gflops) for factor  =       83.622632       17.185482

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =     30

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.011005
     time (cpu & wall) for matrix distrib.   =        0.015625        0.045824
     time (cpu & wall) for numeric factor    =        0.078125        0.087342
     computational rate (gflops) for factor  =       16.724526       14.959711

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =     31

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.010849
     time (cpu & wall) for matrix distrib.   =        0.031250        0.048276
     time (cpu & wall) for numeric factor    =        0.109375        0.098241
     computational rate (gflops) for factor  =       11.946090       13.300024

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =     32

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.010991
     time (cpu & wall) for matrix distrib.   =        0.046875        0.047271
     time (cpu & wall) for numeric factor    =        0.046875        0.082048
     computational rate (gflops) for factor  =       27.874211       15.924888

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =     33

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.010893
     time (cpu & wall) for matrix distrib.   =        0.031250        0.042315
     time (cpu & wall) for numeric factor    =        0.093750        0.098186
     computational rate (gflops) for factor  =       13.937105       13.307460
     time (cpu & wall) for numeric solve     =        0.046875        0.009113
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =     34

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.008097
     time (cpu & wall) for matrix distrib.   =        0.015625        0.051909
     time (cpu & wall) for numeric factor    =        0.031250        0.088608
     computational rate (gflops) for factor  =       41.811316       14.745954

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =     35

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.010887
     time (cpu & wall) for matrix distrib.   =        0.046875        0.053665
     time (cpu & wall) for numeric factor    =        0.046875        0.093098
     computational rate (gflops) for factor  =       27.874211       14.034772

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =     36

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.010903
     time (cpu & wall) for matrix distrib.   =        0.031250        0.046987
     time (cpu & wall) for numeric factor    =        0.078125        0.088135
     computational rate (gflops) for factor  =       16.724526       14.825042
     time (cpu & wall) for numeric solve     =        0.015625        0.008260
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =     37

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.011123
     time (cpu & wall) for matrix distrib.   =        0.031250        0.045266
     time (cpu & wall) for numeric solve     =        0.015625        0.009163
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =     38

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.010950
     time (cpu & wall) for matrix distrib.   =        0.015625        0.069563
     time (cpu & wall) for numeric factor    =        0.093750        0.113903
     computational rate (gflops) for factor  =       13.937105       11.471226

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =     39

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.011007
     time (cpu & wall) for matrix distrib.   =        0.015625        0.046758
     time (cpu & wall) for numeric factor    =        0.078125        0.096922
     computational rate (gflops) for factor  =       16.724526       13.480925

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB





  Performance statistics for DSP solver: icalls =     40

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           46642
     no. of nonzeroes in lower triangle of a =         1090169
     no. of nonzeroes in the factor l        =         7553628
     ratio of nonzeroes in factor (min/max)  =          0.8869
     number of super nodes                   =            1670
     maximum order of a front matrix         =             443
     maximum size of a front matrix          =           98346
     maximum size of a front trapezoid       =           76191
     no. of floating point ops for factor    =      1.3066D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9089
     ratio of allocated memory (max/min)     =          1.1204
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.005723
     time (cpu & wall) for matrix distrib.   =        0.031250        0.048541

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        163840.        1. MB        157156.        1. MB
                95-   1        163840.        1. MB        159707.        1. MB
                95-   2        163840.        1. MB        140010.        1. MB
                95-   3        163840.        1. MB        143543.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        655360.        5. MB        600416.        5. MB


  Solver Memory allocated on core    0       =       32.680 MB
  Solver Memory allocated on core    1       =       33.083 MB
  Solver Memory allocated on core    2       =       29.527 MB
  Solver Memory allocated on core    3       =       30.165 MB
  Total Solver Memory allocated by all cores =      125.454 MB

